apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: getting-started
  name: getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: getting-started
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: getting-started
    spec:
      containers:
        - image: sofiaponte/angular-getting-started:v1
          name: getting-started
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always
status: {}
